import { nanoid } from "@reduxjs/toolkit";
export const filterArr = [
	{
		name: "Position",
		value: "",
		key: "position",
	},
	{
		name: "Name",
		value: "",
		key: "name",
	},
	{
		name: "Office",
		value: "",
		key: "office",
	},
	{
		name: "Age",
		value: "",
		key: "age",
	},
	{
		name: "Start Date",
		value: "",
		key: "startDate",
	},
	{
		name: "Salary",
		value: "",
		key: "salary",
	},
	{
		name: "Status",
		value: "",
		key: "status",
	},
];
export const titleTable = [
	{
		id: "tt8",
		title: "Option",
		name: "Option",
		statusDisplay: true,
	},
	{
		id: "tt1",
		title: "Name",
		name: "name",
		statusDisplay: true,
	},
	{
		id: "tt2",
		title: "Position",
		name: "position",
		statusDisplay: true,
	},
	{
		id: "tt3",
		title: "Office",
		name: "office",
		statusDisplay: true,
	},
	{
		id: "tt4",
		title: "Age",
		name: "age",
		statusDisplay: true,
	},

	{
		id: "tt5",
		title: "Start Date",
		name: "startDate",
		statusDisplay: true,
	},
	{
		id: "tt6",
		title: "Salary",
		name: "Salary",
		statusDisplay: true,
	},
	{
		id: "tt7",
		title: "Status",
		name: "status",
		statusDisplay: true,
	},
	{
		id: "tt9",
		title: "Action",
		name: "action",
		statusDisplay: true,
	},
];
export const init = [
	{
		id: nanoid(),
		name: "Anh",
		position: "Developer",
		office: "Ha Noi",
		age: 23,
		startDate: "10/2/2000",
		salary: 13300,
		status: "enable",
		selected: false,
	},
	{
		id: nanoid(),
		name: "Ngoc",
		position: "Staff",
		office: "Ha Nam",
		age: 24,
		startDate: "11/24/1999",
		salary: 5300,
		status: "enable",
		selected: false,
	},
	{
		id: nanoid(),
		name: "Duong",
		position: "Content",
		office: "Hai Phong",
		age: 25,
		startDate: "3/27/1998",
		salary: 6700,
		status: "enable",
		selected: false,
	},
	{
		id: nanoid(),
		name: "An",
		position: "Blogger",
		office: "Ha Tay ",
		age: 26,
		startDate: "12/2/1997",
		salary: 8500,
		status: "enable",
		selected: false,
	},
	// {
	// 	id: nanoid(),
	// 	name: "Dong",
	// 	position: "Bussiness",
	// 	office: "Son La",
	// 	age: 27,
	// 	startDate: "8/2/1980",
	// 	salary: 8500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ngan",
	// 	position: "Saler",
	// 	office: "Son Tay",
	// 	age: 28,
	// 	startDate: "12/2/2002",
	// 	salary: 9500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Xoan",
	// 	position: "SEO",
	// 	office: "Da Nang",
	// 	age: 29,
	// 	startDate: "12/7/2005",
	// 	salary: 10700,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ket",
	// 	position: "Teacher",
	// 	office: "Tam Chuc",
	// 	age: 30,
	// 	startDate: "7/8/2002",
	// 	salary: 11500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Tuan",
	// 	position: "Law",
	// 	office: "Binh Duong",
	// 	age: 31,
	// 	startDate: "7/2/2002",
	// 	salary: 26000,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Hai12",
	// 	position: "Leader",
	// 	office: "Hai Duong",
	// 	age: 22,
	// 	startDate: "11/23/2000",
	// 	salary: 12300,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Anh43",
	// 	position: "Developer",
	// 	office: "Ha Noi",
	// 	age: 23,
	// 	startDate: "10/2/2000",
	// 	salary: 13300,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ngoc4",
	// 	position: "Staff",
	// 	office: "Ha Nam",
	// 	age: 24,
	// 	startDate: "11/24/1999",
	// 	salary: 5300,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Duong",
	// 	position: "Content",
	// 	office: "Hai Phong",
	// 	age: 25,
	// 	startDate: "3/27/1998",
	// 	salary: 6700,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "An",
	// 	position: "Blogger",
	// 	office: "Ha Nam",
	// 	age: 26,
	// 	startDate: "12/2/1997",
	// 	salary: 8500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Dong",
	// 	position: "Bussiness",
	// 	office: "Son La",
	// 	age: 27,
	// 	startDate: "8/2/1980",
	// 	salary: 8500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ngan",
	// 	position: "Saler",
	// 	office: "Son Tay",
	// 	age: 28,
	// 	startDate: "12/2/2002",
	// 	salary: 9500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Xoan",
	// 	position: "SEO",
	// 	office: "Da Nang",
	// 	age: 29,
	// 	startDate: "12/7/2005",
	// 	salary: 10700,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ket",
	// 	position: "Teacher",
	// 	office: "Tam Chuc",
	// 	age: 30,
	// 	startDate: "7/8/2002",
	// 	salary: 11500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Tuan",
	// 	position: "Law",
	// 	office: "Binh Duong",
	// 	age: 31,
	// 	startDate: "7/2/2002",
	// 	salary: 26000,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Hai",
	// 	position: "Leader",
	// 	office: "Hai Duong",
	// 	age: 22,
	// 	startDate: "11/23/2000",
	// 	salary: 12300,
	// 	selected: false,
	// 	status: "enable",
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Anh",
	// 	position: "Developer",
	// 	office: "Ha Noi",
	// 	age: 23,
	// 	startDate: "10/2/2000",
	// 	salary: 13300,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ngoc",
	// 	position: "Staff",
	// 	office: "Ha Nam",
	// 	age: 24,
	// 	startDate: "11/24/1999",
	// 	salary: 5300,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Duong",
	// 	position: "Content",
	// 	office: "Hai Phong",
	// 	age: 25,
	// 	startDate: "3/27/1998",
	// 	salary: 6700,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "An",
	// 	position: "Blogger",
	// 	office: "Viet Nam",
	// 	age: 26,
	// 	startDate: "12/2/1997",
	// 	salary: 8500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Dong",
	// 	position: "Bussiness",
	// 	office: "Son La",
	// 	age: 27,
	// 	startDate: "8/2/1980",
	// 	salary: 8500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ngan",
	// 	position: "Saler",
	// 	office: "Son Tay",
	// 	age: 28,
	// 	startDate: "12/2/2002",
	// 	salary: 9500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Xoan",
	// 	position: "SEO",
	// 	office: "Da Nang",
	// 	age: 29,
	// 	startDate: "12/7/2005",
	// 	salary: 10700,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ket",
	// 	position: "Teacher",
	// 	office: "Tam Chuc",
	// 	age: 30,
	// 	startDate: "7/8/2002",
	// 	salary: 11500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Tuan",
	// 	position: "Law",
	// 	office: "Binh Duong",
	// 	age: 31,
	// 	startDate: "7/2/2002",
	// 	salary: 26000,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Hai",
	// 	position: "Leader",
	// 	office: "Hai Duong",
	// 	age: 22,
	// 	startDate: "11/23/2000",
	// 	salary: 12300,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Anh",
	// 	position: "Developer",
	// 	office: "Ha Noi",
	// 	age: 23,
	// 	startDate: "10/2/2000",
	// 	salary: 13300,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ngoc",
	// 	position: "Staff",
	// 	office: "Ha Nam",
	// 	age: 24,
	// 	startDate: "11/24/1999",
	// 	salary: 5300,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Duong",
	// 	position: "Content",
	// 	office: "Hai Phong",
	// 	age: 25,
	// 	startDate: "3/27/1998",
	// 	salary: 6700,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "An",
	// 	position: "Blogger",
	// 	office: "Ha Noi",
	// 	age: 26,
	// 	startDate: "12/2/1997",
	// 	salary: 8500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Dong",
	// 	position: "Bussiness",
	// 	office: "Son La",
	// 	age: 27,
	// 	startDate: "8/2/1980",
	// 	salary: 8500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ngan",
	// 	position: "Saler",
	// 	office: "Son Tay",
	// 	age: 28,
	// 	startDate: "12/2/2002",
	// 	salary: 9500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Xoan",
	// 	position: "SEO",
	// 	office: "Da Nang",
	// 	age: 29,
	// 	startDate: "12/7/2005",
	// 	salary: 10700,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Ket",
	// 	position: "Teacher",
	// 	office: "Tam Chuc",
	// 	age: 30,
	// 	startDate: "7/8/2002",
	// 	salary: 11500,
	// 	status: "enable",
	// 	selected: false,
	// },
	// {
	// 	id: nanoid(),
	// 	name: "Tuan",
	// 	position: "Law",
	// 	office: "Binh Duong",
	// 	age: 31,
	// 	startDate: "7/2/2002",
	// 	salary: 26000,
	// 	status: "enable",
	// 	selected: false,
	// },
];
